### ISSUE TITLE
USDT Referenda page fails to load in Chrome

### ISSUE THREAD

**Issue by davidsemakula** [polkassembly/polkassembly#1608]
Referenda page: https://polkadot.polkassembly.io/referenda/779

I was able to load this page and make edits to the proposal yesterday (16/May/24), but can't get it to load today in Chrome.
It loads in Firefox, but Firefox also complains about the page being slow (at least on the first load).

The equivalent page works fine on Subsquare (see https://polkadot.subsquare.io/referenda/779).

Something notable is a referenda (https://polkadot.polkassembly.io/referenda/619) with very similar text from 27/Mar/24 (it's already approved/enacted), is also now failing to load in Chrome. So I think the issue *may* just be related to a recent change in the markdown renderer/editor, because this older page worked fine during it's deciding and confirmation period - the equivalent page also still loads fine on Subsquare (https://polkadot.subsquare.io/referenda/619).

Anyway, this issue completely prevents any actions on the proposal in Chrome (including voting and editing), so a swift resolution would be highly appreciated 🙂 

Chrome version is 125.0.6422.61

**Comment by jasmeets-6575** [comment]
Hi David,

The issue with the USDT Referenda page failing to load in Chrome has been fixed. You should now be able to access and interact with the page without any problems. Please let us know if you encounter any further issues.

Best regards,
PolkAssembly Team

**Comment by davidsemakula** [comment]
Hi @jasmeets-6575 

Thanks for taking the time to look into the issue.
So I've just tested both proposal pages for [779](https://polkadot.polkassembly.io/referenda/779) and [619](https://polkadot.polkassembly.io/referenda/619), and the issue still persists for me on Chrome (and Safari) with cache disabled.

The proposal [779](https://polkadot.polkassembly.io/referenda/779) has passed at this point, so I can't testing the voting anymore, but I can still see that the page never becomes interactive (e.g. links are not clickable), elements (especially right and bottom section) never fully load, and Chrome still eventually raises a "Page Unresponsive" popup.

Here's the version and OS info for the browsers I've tested with:
Chrome on macOS: Version 125.0.6422.142 (Official Build) (arm64)
Safari on macOS: Version 17.4 (19618.1.15.11.12)
Chrome Windows: Version 125.0.6422.142 (Official Build) (64-bit)

LMK if I can provide any more info to help you reproduce the issue.

**Comment by davidsemakula** [comment]
@jasmeets-6575 sorry for pinging again, but can you re-open this issue? it doesn't appear to be solved to me.

**Comment by Swapnil-Sagar** [comment]
Hi @davidsemakula , 
We'll investigate why the referenda pages aren't loading in Chrome and why Firefox is slow. It might be related to recent changes in the markdown renderer/editor.

We'll prioritise resolving this to restore functionality in Chrome and improve performance.

Appreciate your patience!

Best,
Polkassembly Team

**Comment by davidsemakula** [comment]
Hi @Swapnil-Sagar,
just checking if you've had any luck with this issue, seems to still be present for me on Chrome.
Thanks!
